package com.observeai.platform.realtime.neutrino.enums;

public enum CallProcessingEvent {
    CALL_AUDIO_REQUEST,
    DEEPGRAM_SERVICE_RESPONSE,

    KWS_PROCESSING_SKIPPED,
    KWS_PROCESSING_RESPONSE,

    SILENCE_HTV_PROCESSING_SKIPPED,
    SILENCE_HTV_PROCESSING_RESPONSE,

    NLP_PROCESSING_SKIPPED,
    NLP_PROCESSING_RESPONSE,

    ADVANCED_MOMENT_PROCESSING_RESPONSE,
    ADVANCED_MOMENT_PROCESSING_SKIPPED
}
